// Code generated by MockGen. DO NOT EDIT.
// Source: go-hris/internal/company (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock/company_repo_mock.go -package=mock . Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	company "go-hris/internal/company"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *company.Company) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// DeleteRegistration mocks base method.
func (m *MockRepository) DeleteRegistration(ctx context.Context, companyID uuid.UUID, regType company.RegistrationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistration", ctx, companyID, regType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistration indicates an expected call of DeleteRegistration.
func (mr *MockRepositoryMockRecorder) DeleteRegistration(ctx, companyID, regType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistration", reflect.TypeOf((*MockRepository)(nil).DeleteRegistration), ctx, companyID, regType)
}

// GetByEmail mocks base method.
func (m *MockRepository) GetByEmail(ctx context.Context, email string) (*company.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*company.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*company.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*company.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetRegistrationsByCompanyID mocks base method.
func (m *MockRepository) GetRegistrationsByCompanyID(ctx context.Context, companyID uuid.UUID) ([]company.CompanyRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationsByCompanyID", ctx, companyID)
	ret0, _ := ret[0].([]company.CompanyRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationsByCompanyID indicates an expected call of GetRegistrationsByCompanyID.
func (mr *MockRepositoryMockRecorder) GetRegistrationsByCompanyID(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationsByCompanyID", reflect.TypeOf((*MockRepository)(nil).GetRegistrationsByCompanyID), ctx, companyID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *company.Company) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1)
}

// UpsertRegistration mocks base method.
func (m *MockRepository) UpsertRegistration(ctx context.Context, reg *company.CompanyRegistration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRegistration", ctx, reg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRegistration indicates an expected call of UpsertRegistration.
func (mr *MockRepositoryMockRecorder) UpsertRegistration(ctx, reg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRegistration", reflect.TypeOf((*MockRepository)(nil).UpsertRegistration), ctx, reg)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *gorm.DB) company.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(company.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
