// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go
//
// Generated by this command:
//
//	mockgen -source=user_service.go -destination=mock/user_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	user "go-hris/internal/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockService) ChangePassword(ctx context.Context, companyID, userID, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, companyID, userID, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockServiceMockRecorder) ChangePassword(ctx, companyID, userID, currentPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockService)(nil).ChangePassword), ctx, companyID, userID, currentPassword, newPassword)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, companyID string, req user.CreateUserRequest) (user.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, companyID, req)
	ret0, _ := ret[0].(user.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, companyID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, companyID, req)
}

// ForceResetPassword mocks base method.
func (m *MockService) ForceResetPassword(ctx context.Context, companyID, userID, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceResetPassword", ctx, companyID, userID, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceResetPassword indicates an expected call of ForceResetPassword.
func (mr *MockServiceMockRecorder) ForceResetPassword(ctx, companyID, userID, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceResetPassword", reflect.TypeOf((*MockService)(nil).ForceResetPassword), ctx, companyID, userID, newPassword)
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context, companyID string) ([]user.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, companyID)
	ret0, _ := ret[0].([]user.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx, companyID)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, companyID, id string) (user.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, companyID, id)
	ret0, _ := ret[0].(user.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, companyID, id)
}

// GetCompanyUsers mocks base method.
func (m *MockService) GetCompanyUsers(ctx context.Context, companyID string) ([]user.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyUsers", ctx, companyID)
	ret0, _ := ret[0].([]user.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyUsers indicates an expected call of GetCompanyUsers.
func (mr *MockServiceMockRecorder) GetCompanyUsers(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyUsers", reflect.TypeOf((*MockService)(nil).GetCompanyUsers), ctx, companyID)
}

// ResetPassword mocks base method.
func (m *MockService) ResetPassword(ctx context.Context, companyID, userID, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, companyID, userID, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockServiceMockRecorder) ResetPassword(ctx, companyID, userID, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockService)(nil).ResetPassword), ctx, companyID, userID, newPassword)
}

// ToggleStatus mocks base method.
func (m *MockService) ToggleStatus(ctx context.Context, companyID, id string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleStatus", ctx, companyID, id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleStatus indicates an expected call of ToggleStatus.
func (mr *MockServiceMockRecorder) ToggleStatus(ctx, companyID, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleStatus", reflect.TypeOf((*MockService)(nil).ToggleStatus), ctx, companyID, id, isActive)
}
