// Code generated by MockGen. DO NOT EDIT.
// Source: leave_repo.go
//
// Generated by this command:
//
//	mockgen -source=leave_repo.go -destination=mock/leave_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	leave "go-hris/internal/leave"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, l *leave.Leave) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, l)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, companyID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, companyID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, companyID, id)
}

// EmployeeBelongsToCompany mocks base method.
func (m *MockRepository) EmployeeBelongsToCompany(ctx context.Context, companyID, employeeID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmployeeBelongsToCompany", ctx, companyID, employeeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmployeeBelongsToCompany indicates an expected call of EmployeeBelongsToCompany.
func (mr *MockRepositoryMockRecorder) EmployeeBelongsToCompany(ctx, companyID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmployeeBelongsToCompany", reflect.TypeOf((*MockRepository)(nil).EmployeeBelongsToCompany), ctx, companyID, employeeID)
}

// FindAllByCompany mocks base method.
func (m *MockRepository) FindAllByCompany(ctx context.Context, companyID string) ([]leave.Leave, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByCompany", ctx, companyID)
	ret0, _ := ret[0].([]leave.Leave)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByCompany indicates an expected call of FindAllByCompany.
func (mr *MockRepositoryMockRecorder) FindAllByCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByCompany", reflect.TypeOf((*MockRepository)(nil).FindAllByCompany), ctx, companyID)
}

// FindAllByCompanyAndEmployee mocks base method.
func (m *MockRepository) FindAllByCompanyAndEmployee(ctx context.Context, companyID, employeeID string) ([]leave.Leave, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByCompanyAndEmployee", ctx, companyID, employeeID)
	ret0, _ := ret[0].([]leave.Leave)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByCompanyAndEmployee indicates an expected call of FindAllByCompanyAndEmployee.
func (mr *MockRepositoryMockRecorder) FindAllByCompanyAndEmployee(ctx, companyID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByCompanyAndEmployee", reflect.TypeOf((*MockRepository)(nil).FindAllByCompanyAndEmployee), ctx, companyID, employeeID)
}

// FindByIDAndCompany mocks base method.
func (m *MockRepository) FindByIDAndCompany(ctx context.Context, companyID, id string) (*leave.Leave, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDAndCompany", ctx, companyID, id)
	ret0, _ := ret[0].(*leave.Leave)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDAndCompany indicates an expected call of FindByIDAndCompany.
func (mr *MockRepositoryMockRecorder) FindByIDAndCompany(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDAndCompany", reflect.TypeOf((*MockRepository)(nil).FindByIDAndCompany), ctx, companyID, id)
}

// HasOverlappingPeriod mocks base method.
func (m *MockRepository) HasOverlappingPeriod(ctx context.Context, companyID, employeeID string, startDate, endDate time.Time, excludeID *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasOverlappingPeriod", ctx, companyID, employeeID, startDate, endDate, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasOverlappingPeriod indicates an expected call of HasOverlappingPeriod.
func (mr *MockRepositoryMockRecorder) HasOverlappingPeriod(ctx, companyID, employeeID, startDate, endDate, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasOverlappingPeriod", reflect.TypeOf((*MockRepository)(nil).HasOverlappingPeriod), ctx, companyID, employeeID, startDate, endDate, excludeID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, l *leave.Leave) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, l)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *sql.Tx) leave.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(leave.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
