// Code generated by MockGen. DO NOT EDIT.
// Source: leave_service.go
//
// Generated by this command:
//
//	mockgen -source=leave_service.go -destination=mock/leave_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	leave "go-hris/internal/leave"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockService) Approve(ctx context.Context, companyID, actorID, id string) (leave.LeaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, companyID, actorID, id)
	ret0, _ := ret[0].(leave.LeaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Approve indicates an expected call of Approve.
func (mr *MockServiceMockRecorder) Approve(ctx, companyID, actorID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockService)(nil).Approve), ctx, companyID, actorID, id)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, companyID, actorID string, req leave.CreateLeaveRequest) (leave.LeaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, companyID, actorID, req)
	ret0, _ := ret[0].(leave.LeaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, companyID, actorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, companyID, actorID, req)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, companyID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, companyID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, companyID, id)
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context, companyID, actorID string, canReadAll bool) ([]leave.LeaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, companyID, actorID, canReadAll)
	ret0, _ := ret[0].([]leave.LeaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx, companyID, actorID, canReadAll any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx, companyID, actorID, canReadAll)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, companyID, id string) (leave.LeaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, companyID, id)
	ret0, _ := ret[0].(leave.LeaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, companyID, id)
}

// Reject mocks base method.
func (m *MockService) Reject(ctx context.Context, companyID, actorID, id, rejectionReason string) (leave.LeaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, companyID, actorID, id, rejectionReason)
	ret0, _ := ret[0].(leave.LeaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockServiceMockRecorder) Reject(ctx, companyID, actorID, id, rejectionReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockService)(nil).Reject), ctx, companyID, actorID, id, rejectionReason)
}

// Submit mocks base method.
func (m *MockService) Submit(ctx context.Context, companyID, actorID, id string) (leave.LeaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, companyID, actorID, id)
	ret0, _ := ret[0].(leave.LeaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockServiceMockRecorder) Submit(ctx, companyID, actorID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockService)(nil).Submit), ctx, companyID, actorID, id)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, companyID, actorID, id string, req leave.UpdateLeaveRequest) (leave.LeaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, companyID, actorID, id, req)
	ret0, _ := ret[0].(leave.LeaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, companyID, actorID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, companyID, actorID, id, req)
}
