// Code generated by MockGen. DO NOT EDIT.
// Source: rbac_repo.go
//
// Generated by this command:
//
//	mockgen -source=rbac_repo.go -destination=mock/rbac_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	rbac "go-hris/internal/rbac"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetEmployeeRoles mocks base method.
func (m *MockRepository) GetEmployeeRoles(companyID string) ([]rbac.EmployeeRoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeRoles", companyID)
	ret0, _ := ret[0].([]rbac.EmployeeRoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeRoles indicates an expected call of GetEmployeeRoles.
func (mr *MockRepositoryMockRecorder) GetEmployeeRoles(companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeRoles", reflect.TypeOf((*MockRepository)(nil).GetEmployeeRoles), companyID)
}

// GetRolePermissions mocks base method.
func (m *MockRepository) GetRolePermissions(companyID string) ([]rbac.RolePermissionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", companyID)
	ret0, _ := ret[0].([]rbac.RolePermissionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockRepositoryMockRecorder) GetRolePermissions(companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockRepository)(nil).GetRolePermissions), companyID)
}
