// Code generated by MockGen. DO NOT EDIT.
// Source: rbac_service.go
//
// Generated by this command:
//
//	mockgen -source=rbac_service.go -destination=mock/rbac_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	rbac "go-hris/internal/rbac"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockService) Enforce(req rbac.EnforceRequest) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockServiceMockRecorder) Enforce(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockService)(nil).Enforce), req)
}

// LoadCompanyPolicy mocks base method.
func (m *MockService) LoadCompanyPolicy(companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCompanyPolicy", companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadCompanyPolicy indicates an expected call of LoadCompanyPolicy.
func (mr *MockServiceMockRecorder) LoadCompanyPolicy(companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCompanyPolicy", reflect.TypeOf((*MockService)(nil).LoadCompanyPolicy), companyID)
}
