// Code generated by MockGen. DO NOT EDIT.
// Source: rbac_service.go
//
// Generated by this command:
//
//	mockgen -source=rbac_service.go -destination=mock/rbac_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "go-hris/internal/domain"
	rbac "go-hris/internal/rbac"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AssignRoleIDToEmployee mocks base method.
func (m *MockService) AssignRoleIDToEmployee(employeeID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleIDToEmployee", employeeID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleIDToEmployee indicates an expected call of AssignRoleIDToEmployee.
func (mr *MockServiceMockRecorder) AssignRoleIDToEmployee(employeeID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleIDToEmployee", reflect.TypeOf((*MockService)(nil).AssignRoleIDToEmployee), employeeID, roleID)
}

// AssignRoleToEmployee mocks base method.
func (m *MockService) AssignRoleToEmployee(companyID, employeeID, roleName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToEmployee", companyID, employeeID, roleName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToEmployee indicates an expected call of AssignRoleToEmployee.
func (mr *MockServiceMockRecorder) AssignRoleToEmployee(companyID, employeeID, roleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToEmployee", reflect.TypeOf((*MockService)(nil).AssignRoleToEmployee), companyID, employeeID, roleName)
}

// CreateRole mocks base method.
func (m *MockService) CreateRole(companyID string, req domain.CreateRoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", companyID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockServiceMockRecorder) CreateRole(companyID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockService)(nil).CreateRole), companyID, req)
}

// DeleteRole mocks base method.
func (m *MockService) DeleteRole(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockServiceMockRecorder) DeleteRole(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockService)(nil).DeleteRole), id)
}

// Enforce mocks base method.
func (m *MockService) Enforce(req domain.EnforceRequest) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockServiceMockRecorder) Enforce(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockService)(nil).Enforce), req)
}

// GetEmployeePermissions mocks base method.
func (m *MockService) GetEmployeePermissions(employeeID, companyID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeePermissions", employeeID, companyID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeePermissions indicates an expected call of GetEmployeePermissions.
func (mr *MockServiceMockRecorder) GetEmployeePermissions(employeeID, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeePermissions", reflect.TypeOf((*MockService)(nil).GetEmployeePermissions), employeeID, companyID)
}

// GetRole mocks base method.
func (m *MockService) GetRole(id string) (*domain.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", id)
	ret0, _ := ret[0].(*domain.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockServiceMockRecorder) GetRole(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockService)(nil).GetRole), id)
}

// GetRoleByName mocks base method.
func (m *MockService) GetRoleByName(companyID, name string) (*domain.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", companyID, name)
	ret0, _ := ret[0].(*domain.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockServiceMockRecorder) GetRoleByName(companyID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockService)(nil).GetRoleByName), companyID, name)
}

// ListPermissions mocks base method.
func (m *MockService) ListPermissions() ([]domain.PermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions")
	ret0, _ := ret[0].([]domain.PermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockServiceMockRecorder) ListPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockService)(nil).ListPermissions))
}

// ListRoles mocks base method.
func (m *MockService) ListRoles(companyID string) ([]domain.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", companyID)
	ret0, _ := ret[0].([]domain.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockServiceMockRecorder) ListRoles(companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockService)(nil).ListRoles), companyID)
}

// LoadCompanyPolicy mocks base method.
func (m *MockService) LoadCompanyPolicy(companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCompanyPolicy", companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadCompanyPolicy indicates an expected call of LoadCompanyPolicy.
func (mr *MockServiceMockRecorder) LoadCompanyPolicy(companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCompanyPolicy", reflect.TypeOf((*MockService)(nil).LoadCompanyPolicy), companyID)
}

// SeedDefaultRoles mocks base method.
func (m *MockService) SeedDefaultRoles(companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeedDefaultRoles", companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SeedDefaultRoles indicates an expected call of SeedDefaultRoles.
func (mr *MockServiceMockRecorder) SeedDefaultRoles(companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeedDefaultRoles", reflect.TypeOf((*MockService)(nil).SeedDefaultRoles), companyID)
}

// UpdateRole mocks base method.
func (m *MockService) UpdateRole(id string, req domain.UpdateRoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockServiceMockRecorder) UpdateRole(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockService)(nil).UpdateRole), id, req)
}

// WithTx mocks base method.
func (m *MockService) WithTx(tx *gorm.DB) rbac.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(rbac.Service)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockServiceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockService)(nil).WithTx), tx)
}
