// Code generated by MockGen. DO NOT EDIT.
// Source: attendance_service.go
//
// Generated by this command:
//
//	mockgen -source=attendance_service.go -destination=mock/attendance_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	attendance "go-hris/internal/attendance"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ClockIn mocks base method.
func (m *MockService) ClockIn(ctx context.Context, companyID, employeeID string, req attendance.ClockInRequest) (attendance.AttendanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClockIn", ctx, companyID, employeeID, req)
	ret0, _ := ret[0].(attendance.AttendanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClockIn indicates an expected call of ClockIn.
func (mr *MockServiceMockRecorder) ClockIn(ctx, companyID, employeeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClockIn", reflect.TypeOf((*MockService)(nil).ClockIn), ctx, companyID, employeeID, req)
}

// ClockOut mocks base method.
func (m *MockService) ClockOut(ctx context.Context, companyID, employeeID string, req attendance.ClockOutRequest) (attendance.AttendanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClockOut", ctx, companyID, employeeID, req)
	ret0, _ := ret[0].(attendance.AttendanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClockOut indicates an expected call of ClockOut.
func (mr *MockServiceMockRecorder) ClockOut(ctx, companyID, employeeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClockOut", reflect.TypeOf((*MockService)(nil).ClockOut), ctx, companyID, employeeID, req)
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context, companyID, actorID string, canReadAll bool) ([]attendance.AttendanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, companyID, actorID, canReadAll)
	ret0, _ := ret[0].([]attendance.AttendanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx, companyID, actorID, canReadAll any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx, companyID, actorID, canReadAll)
}
