// Code generated by MockGen. DO NOT EDIT.
// Source: attendance_repo.go
//
// Generated by this command:
//
//	mockgen -source=attendance_repo.go -destination=mock/attendance_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	attendance "go-hris/internal/attendance"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, a *attendance.Attendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, a)
}

// FindAllByCompany mocks base method.
func (m *MockRepository) FindAllByCompany(ctx context.Context, companyID string) ([]attendance.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByCompany", ctx, companyID)
	ret0, _ := ret[0].([]attendance.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByCompany indicates an expected call of FindAllByCompany.
func (mr *MockRepositoryMockRecorder) FindAllByCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByCompany", reflect.TypeOf((*MockRepository)(nil).FindAllByCompany), ctx, companyID)
}

// FindAllByCompanyAndEmployee mocks base method.
func (m *MockRepository) FindAllByCompanyAndEmployee(ctx context.Context, companyID, employeeID string) ([]attendance.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByCompanyAndEmployee", ctx, companyID, employeeID)
	ret0, _ := ret[0].([]attendance.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByCompanyAndEmployee indicates an expected call of FindAllByCompanyAndEmployee.
func (mr *MockRepositoryMockRecorder) FindAllByCompanyAndEmployee(ctx, companyID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByCompanyAndEmployee", reflect.TypeOf((*MockRepository)(nil).FindAllByCompanyAndEmployee), ctx, companyID, employeeID)
}

// FindByEmployeeAndDate mocks base method.
func (m *MockRepository) FindByEmployeeAndDate(ctx context.Context, companyID, employeeID string, date time.Time) (*attendance.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmployeeAndDate", ctx, companyID, employeeID, date)
	ret0, _ := ret[0].(*attendance.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmployeeAndDate indicates an expected call of FindByEmployeeAndDate.
func (mr *MockRepositoryMockRecorder) FindByEmployeeAndDate(ctx, companyID, employeeID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmployeeAndDate", reflect.TypeOf((*MockRepository)(nil).FindByEmployeeAndDate), ctx, companyID, employeeID, date)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, a *attendance.Attendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, a)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *sql.Tx) attendance.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(attendance.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
