// Code generated by MockGen. DO NOT EDIT.
// Source: employee_repo.go
//
// Generated by this command:
//
//	mockgen -source=employee_repo.go -destination=mock/employee_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	employee "go-hris/internal/employee"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, dept *employee.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dept)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, dept any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, dept)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, companyID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, companyID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, companyID, id)
}

// FindAllByCompany mocks base method.
func (m *MockRepository) FindAllByCompany(ctx context.Context, companyID string) ([]employee.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByCompany", ctx, companyID)
	ret0, _ := ret[0].([]employee.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByCompany indicates an expected call of FindAllByCompany.
func (mr *MockRepositoryMockRecorder) FindAllByCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByCompany", reflect.TypeOf((*MockRepository)(nil).FindAllByCompany), ctx, companyID)
}

// FindByIDAndCompany mocks base method.
func (m *MockRepository) FindByIDAndCompany(ctx context.Context, companyID, id string) (*employee.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDAndCompany", ctx, companyID, id)
	ret0, _ := ret[0].(*employee.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDAndCompany indicates an expected call of FindByIDAndCompany.
func (mr *MockRepositoryMockRecorder) FindByIDAndCompany(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDAndCompany", reflect.TypeOf((*MockRepository)(nil).FindByIDAndCompany), ctx, companyID, id)
}

// GetDepartmentIDByPosition mocks base method.
func (m *MockRepository) GetDepartmentIDByPosition(ctx context.Context, companyID, positionID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentIDByPosition", ctx, companyID, positionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentIDByPosition indicates an expected call of GetDepartmentIDByPosition.
func (mr *MockRepositoryMockRecorder) GetDepartmentIDByPosition(ctx, companyID, positionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentIDByPosition", reflect.TypeOf((*MockRepository)(nil).GetDepartmentIDByPosition), ctx, companyID, positionID)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, dept *employee.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, dept)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, dept any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, dept)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *sql.Tx) employee.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(employee.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
