// Code generated by MockGen. DO NOT EDIT.
// Source: outbox_repo.go
//
// Generated by this command:
//
//	mockgen -source=outbox_repo.go -destination=mock/outbox_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	kafka "go-hris/internal/messaging/kafka"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, event kafka.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, event)
}

// ListPending mocks base method.
func (m *MockOutboxRepository) ListPending(ctx context.Context, limit int) ([]kafka.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, limit)
	ret0, _ := ret[0].([]kafka.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockOutboxRepositoryMockRecorder) ListPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockOutboxRepository)(nil).ListPending), ctx, limit)
}

// MarkFailed mocks base method.
func (m *MockOutboxRepository) MarkFailed(ctx context.Context, id, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkFailed(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkFailed), ctx, id, reason)
}

// MarkSent mocks base method.
func (m *MockOutboxRepository) MarkSent(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockOutboxRepositoryMockRecorder) MarkSent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockOutboxRepository)(nil).MarkSent), ctx, id)
}

// WithTx mocks base method.
func (m *MockOutboxRepository) WithTx(tx *sql.Tx) kafka.OutboxRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(kafka.OutboxRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockOutboxRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockOutboxRepository)(nil).WithTx), tx)
}
