// Code generated by MockGen. DO NOT EDIT.
// Source: go-hris/internal/shared/counter (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock/counter_repo_mock.go -package=mock . Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetNextValue mocks base method.
func (m *MockRepository) GetNextValue(ctx context.Context, companyID, counterType string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextValue", ctx, companyID, counterType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextValue indicates an expected call of GetNextValue.
func (mr *MockRepositoryMockRecorder) GetNextValue(ctx, companyID, counterType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextValue", reflect.TypeOf((*MockRepository)(nil).GetNextValue), ctx, companyID, counterType)
}
