// Code generated by MockGen. DO NOT EDIT.
// Source: payroll_service.go
//
// Generated by this command:
//
//	mockgen -source=payroll_service.go -destination=mock/payroll_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	payroll "go-hris/internal/payroll"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockService) Approve(ctx context.Context, companyID, actorID, id string) (payroll.PayrollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, companyID, actorID, id)
	ret0, _ := ret[0].(payroll.PayrollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Approve indicates an expected call of Approve.
func (mr *MockServiceMockRecorder) Approve(ctx, companyID, actorID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockService)(nil).Approve), ctx, companyID, actorID, id)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, companyID, actorID string, req payroll.CreatePayrollRequest) (payroll.PayrollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, companyID, actorID, req)
	ret0, _ := ret[0].(payroll.PayrollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, companyID, actorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, companyID, actorID, req)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, companyID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, companyID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, companyID, id)
}

// GeneratePayslip mocks base method.
func (m *MockService) GeneratePayslip(ctx context.Context, companyID, id string) (payroll.PayrollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePayslip", ctx, companyID, id)
	ret0, _ := ret[0].(payroll.PayrollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePayslip indicates an expected call of GeneratePayslip.
func (mr *MockServiceMockRecorder) GeneratePayslip(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePayslip", reflect.TypeOf((*MockService)(nil).GeneratePayslip), ctx, companyID, id)
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context, companyID string, filterReq payroll.GetPayrollsFilterRequest) ([]payroll.PayrollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, companyID, filterReq)
	ret0, _ := ret[0].([]payroll.PayrollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx, companyID, filterReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx, companyID, filterReq)
}

// GetBreakdown mocks base method.
func (m *MockService) GetBreakdown(ctx context.Context, companyID, id string) (payroll.PayrollBreakdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBreakdown", ctx, companyID, id)
	ret0, _ := ret[0].(payroll.PayrollBreakdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBreakdown indicates an expected call of GetBreakdown.
func (mr *MockServiceMockRecorder) GetBreakdown(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBreakdown", reflect.TypeOf((*MockService)(nil).GetBreakdown), ctx, companyID, id)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, companyID, id string) (payroll.PayrollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, companyID, id)
	ret0, _ := ret[0].(payroll.PayrollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, companyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, companyID, id)
}

// MarkAsPaid mocks base method.
func (m *MockService) MarkAsPaid(ctx context.Context, companyID, actorID, id string) (payroll.PayrollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPaid", ctx, companyID, actorID, id)
	ret0, _ := ret[0].(payroll.PayrollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAsPaid indicates an expected call of MarkAsPaid.
func (mr *MockServiceMockRecorder) MarkAsPaid(ctx, companyID, actorID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPaid", reflect.TypeOf((*MockService)(nil).MarkAsPaid), ctx, companyID, actorID, id)
}

// Regenerate mocks base method.
func (m *MockService) Regenerate(ctx context.Context, companyID, actorID, id string, req payroll.RegeneratePayrollRequest) (payroll.PayrollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Regenerate", ctx, companyID, actorID, id, req)
	ret0, _ := ret[0].(payroll.PayrollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Regenerate indicates an expected call of Regenerate.
func (mr *MockServiceMockRecorder) Regenerate(ctx, companyID, actorID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Regenerate", reflect.TypeOf((*MockService)(nil).Regenerate), ctx, companyID, actorID, id, req)
}
